#!/usr/bin/env bash

# Basic Build Profile for Apache2 with FireJail
# Made with Copilot AI

set -euo pipefail

PROFILE="/etc/firejail/apache2.profile"

# Detect Apache executable
if command -v apache2 >/dev/null 2>&1; then
    APACHE_BIN="$(command -v apache2)"
elif command -v httpd >/dev/null 2>&1; then
    APACHE_BIN="$(command -v httpd)"
else
    echo "Error: Could not find apache2 or httpd binary."
    exit 1
fi

echo "Detected Apache binary: $APACHE_BIN"
echo "Writing Firejail profile to $PROFILE"

sudo tee "$PROFILE" >/dev/null <<EOF
# Firejail profile for Apache2
# Auto-generated by build-apache2-firejail.sh

# Basic isolation
private
private-tmp
private-dev
nonewprivs

# Seccomp filtering
seccomp

# Drop all capabilities except the one needed to bind to ports <1024
caps.drop all
caps.keep net_bind_service

# Allow only required directories
whitelist /var/www
whitelist /etc/apache2
whitelist /var/log/apache2
whitelist /usr/lib
whitelist /usr/lib64
whitelist /run/apache2
whitelist /run/lock/apache2

# Allow the Apache binary itself
whitelist $APACHE_BIN

# Deny access to home directories
blacklist /home

# Deny access to sensitive system areas
blacklist /root
blacklist /mnt
blacklist /media
blacklist /opt
blacklist /srv

# Networking allowed (Apache needs it)
netfilter

# Keep environment clean
env DISPLAY
EOF

echo "Profile created successfully."
echo "Next step: integrate Firejail with systemd."
