#!/usr/bin/env bash
#
# setup-firejail-apache.sh
#
# This script automates the deployment of a hardened Firejail sandbox
# for Apache2. It performs the following actions:
#
# 1. Detects the Apache executable path (apache2 or httpd).
# 2. Generates a Firejail profile at /etc/firejail/apache2.profile.
# 3. Creates a systemd override so Apache always runs inside Firejail.
# 4. Backs up the original systemd unit override (if any).
# 5. Provides a rollback option to restore the previous configuration.
#
# Usage:
#   ./setup-firejail-apache.sh        # Deploy sandbox
#   ./setup-firejail-apache.sh rollback   # Roll back changes
#
# This script is idempotent and safe to re-run.

set -euo pipefail

PROFILE="/etc/firejail/apache2.profile"
SYSTEMD_DIR="/etc/systemd/system/apache2.service.d"
OVERRIDE_FILE="$SYSTEMD_DIR/override.conf"
BACKUP_FILE="$SYSTEMD_DIR/override.conf.bak"

rollback() {
    echo "[*] Rolling back Firejail Apache integration..."

    if [[ -f "$BACKUP_FILE" ]]; then
        echo "[+] Restoring previous systemd override..."
        sudo mv "$BACKUP_FILE" "$OVERRIDE_FILE"
    else
        echo "[!] No backup override found. Removing override entirely..."
        sudo rm -f "$OVERRIDE_FILE"
    fi

    echo "[+] Removing Firejail profile..."
    sudo rm -f "$PROFILE"

    echo "[+] Reloading systemd..."
    sudo systemctl daemon-reload

    echo "[+] Restarting Apache..."
    sudo systemctl restart apache2 || sudo systemctl restart httpd

    echo "[✓] Rollback complete."
    exit 0
}

if [[ "${1:-}" == "rollback" ]]; then
    rollback
fi

echo "[*] Detecting Apache executable..."

if command -v apache2 >/dev/null 2>&1; then
    APACHE_BIN="$(command -v apache2)"
    SERVICE="apache2"
elif command -v httpd >/dev/null 2>&1; then
    APACHE_BIN="$(command -v httpd)"
    SERVICE="httpd"
else
    echo "[!] Error: Could not find apache2 or httpd binary."
    exit 1
fi

echo "[+] Apache binary detected: $APACHE_BIN"
echo "[*] Writing Firejail profile to $PROFILE..."

sudo tee "$PROFILE" >/dev/null <<EOF
# Firejail profile for Apache2
# Auto-generated by setup-firejail-apache.sh

private
private-tmp
private-dev
nonewprivs
seccomp

caps.drop all
caps.keep net_bind_service

whitelist /var/www
whitelist /etc/apache2
whitelist /var/log/apache2
whitelist /usr/lib
whitelist /usr/lib64
whitelist /run/apache2
whitelist /run/lock/apache2
whitelist $APACHE_BIN

blacklist /home
blacklist /root
blacklist /mnt
blacklist /media
blacklist /opt
blacklist /srv

netfilter
env DISPLAY
EOF

echo "[+] Firejail profile created."

echo "[*] Preparing systemd override..."

sudo mkdir -p "$SYSTEMD_DIR"

if [[ -f "$OVERRIDE_FILE" ]]; then
    echo "[*] Backing up existing override..."
    sudo cp "$OVERRIDE_FILE" "$BACKUP_FILE"
fi

echo "[*] Writing new override to $OVERRIDE_FILE..."

sudo tee "$OVERRIDE_FILE" >/dev/null <<EOF
[Service]
ExecStart=
ExecStart=/usr/bin/firejail --profile=$PROFILE $APACHE_BIN -DFOREGROUND
EOF

echo "[+] Systemd override installed."

echo "[*] Reloading systemd..."
sudo systemctl daemon-reload

echo "[*] Restarting Apache inside Firejail..."
sudo systemctl restart "$SERVICE"

echo "[✓] Apache is now sandboxed with Firejail."
echo "[✓] To roll back, run: $0 rollback"
